# CMake generated Testfile for 
# Source directory: /nobackup/swapnilh/mod-single-repo/Immutable-Datastructure-c++/test
# Build directory: /nobackup/swapnilh/mod-single-repo/Immutable-Datastructure-c++/build_vacation/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test/array-default "array-default")
add_test(test/array-gc "array-gc")
add_test(test/array_transient-default "array_transient-default")
add_test(test/array_transient-gc "array_transient-gc")
add_test(test/box-default "box-default")
add_test(test/box-gc "box-gc")
add_test(test/box-recursive "box-recursive")
add_test(test/box-vector-of-boxes-transient "box-vector-of-boxes-transient")
add_test(test/detail-type_traits "detail-type_traits")
add_test(test/experimental-dvektor "experimental-dvektor")
add_test(test/flex_vector-B3-BL0 "flex_vector-B3-BL0")
add_test(test/flex_vector-B3-BL3 "flex_vector-B3-BL3")
add_test(test/flex_vector-default "flex_vector-default")
add_test(test/flex_vector-fuzzed-0 "flex_vector-fuzzed-0")
add_test(test/flex_vector-fuzzed-1 "flex_vector-fuzzed-1")
add_test(test/flex_vector-fuzzed-2 "flex_vector-fuzzed-2")
add_test(test/flex_vector-fuzzed-3 "flex_vector-fuzzed-3")
add_test(test/flex_vector-fuzzed-4 "flex_vector-fuzzed-4")
add_test(test/flex_vector-gc "flex_vector-gc")
add_test(test/flex_vector-issue-45 "flex_vector-issue-45")
add_test(test/flex_vector-issue-47 "flex_vector-issue-47")
add_test(test/flex_vector-regular-B3-BL3 "flex_vector-regular-B3-BL3")
add_test(test/flex_vector-regular-default "flex_vector-regular-default")
add_test(test/flex_vector_transient-B3-BL0 "flex_vector_transient-B3-BL0")
add_test(test/flex_vector_transient-default "flex_vector_transient-default")
add_test(test/flex_vector_transient-gc "flex_vector_transient-gc")
add_test(test/flex_vector_transient-regular-default "flex_vector_transient-regular-default")
add_test(test/flex_vector_transient-regular-gc "flex_vector_transient-regular-gc")
add_test(test/map-B3 "map-B3")
add_test(test/map-default "map-default")
add_test(test/map-gc "map-gc")
add_test(test/memory-heaps "memory-heaps")
add_test(test/memory-refcounts "memory-refcounts")
add_test(test/set-B3 "set-B3")
add_test(test/set-default "set-default")
add_test(test/set-gc "set-gc")
add_test(test/vector-B3-BL0 "vector-B3-BL0")
add_test(test/vector-B3-BL2 "vector-B3-BL2")
add_test(test/vector-B3-BL3 "vector-B3-BL3")
add_test(test/vector-B3-BL4 "vector-B3-BL4")
add_test(test/vector-default "vector-default")
add_test(test/vector-gc "vector-gc")
add_test(test/vector-issue-16 "vector-issue-16")
add_test(test/vector-issue-46 "vector-issue-46")
add_test(test/vector_transient-B3-BL0 "vector_transient-B3-BL0")
add_test(test/vector_transient-default "vector_transient-default")
add_test(test/vector_transient-gc "vector_transient-gc")
